name: Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install OS dependencies
        run: |
          sudo apt-get install -yqq libsndfile1 libsndfile1-dev
      - name: Install Python dependencies
        run: |
          python -m pip install -U 'pip<20'
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi

      - name: Test in-tree code with pytest
        run: |
          python -m pytest -v tests/


  experiments:

    runs-on: ubuntu-latest
    env:
      python-version: '3.10'
    strategy:
      matrix:
        depth_limiter: [
            { experiment: min_samples_leaf, config: 'MIN_SAMPLES_LEAF=1,2,4,8,16,32,64,128' },
            { experiment: min_samples_split, config: 'MIN_SAMPLES_SPLIT=2,4,8,16,32,64,128,256' },
            { experiment: max_leaf_nodes, config: 'MAX_LEAF_NODES=3,10,32,100,320,1000,3200,10000' },
            { experiment: min_impurity_decrease, config: 'MIN_IMPURITY_DECREASE=0.00,0.05,0.10,0.15,0.20,0.25,0.30,0.35,0.40,0.45,0.50' },
            { experiment: max_depth, config: 'MAX_DEPTH=20,18,16,14,12,10,8,6,4,2' },
        ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
      - name: Install OS dependencies
        run: |
          sudo apt-get install -yqq libsndfile1 libsndfile1-dev
      - name: Install Python dependencies
        run: |
          python -m pip install -U 'pip<20'
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi

      - name: Cache dataset
        id: cache-openml-cc18
        uses: actions/cache@v4
        with:
          path: data/raw/openml-cc18
          key: openml-cc18-1

      - name: Download data
        run: |
          python -m src.data.openml.download

      - name: Run experiments
        run: |
           EXPERIMENT=${{ matrix.depth_limiter.experiment }} ${{ matrix.depth_limiter.config }} REPETITIONS=1 TREES=10 python -m src.experiments.run

      - uses: actions/upload-artifact@v4
        with:
          name: openml-cc18-results-depth-limiter-${{ matrix.depth_limiter.experiment }}
          path: output/results/
